// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

enum {0}Controls
{{
// skip low-numbered control ids that overlap Windows controls ids like IDOK and IDCANCEL
{1}
}};

HRESULT Load{0}Theme(
    __in THEME* pTheme,
    __in HWND hwndParent
    );

